#!/usr/bin/env bash

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Adapt the current terminal to use develop dotly
##?
##? Usage:
##?   afterinstall java
docs::parse "$@"

case $1 in
"java")
  sudo ln -sfn /usr/local/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
  sudo ln -sfn /usr/local/opt/openjdk@8/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-8.jdk
  sudo ln -sfn /usr/local/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk
  ;;
*)
  exit 1
  ;;
esac